config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('sentry-debug/', trigger_error),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms.views import HomeView

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views


app_name = "rooms"

urlpatterns = [
    path("search/", views.SearchView.as_view(), name="search"),
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.DetailRoomView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.UploadPhotoView.as_view(), name="upload-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
]

rooms/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core.models import AbstractTimeStamped
from cal import Calendar

class AbstractItem(AbstractTimeStamped):

    """Abstract Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """RoomType Model Definition"""

    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstractItem):

    """Amenity Model Definition"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):
    """Facility Model Definition"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):
    """HouseRule Model Definition"""

    class Meta:
        verbose_name = "House Rule"


class Photo(AbstractTimeStamped):
    """Photo Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", on_delete=models.CASCADE, related_name="photos")

    def __str__(self):
        return self.caption


class Room(AbstractTimeStamped):

    """Room Model Definition"""

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField(help_text="How many people will be staying?")
    beds = models.IntegerField()
    baths = models.IntegerField()
    bedrooms = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", on_delete=models.PROTECT, related_name="rooms"
    )
    room_type = models.ForeignKey(
        "RoomType", on_delete=models.SET_NULL, null=True, related_name="rooms"
    )
    amenities = models.ManyToManyField(Amenity, blank=True, related_name="rooms")
    facilities = models.ManyToManyField(Facility, blank=True, related_name="rooms")
    house_rules = models.ManyToManyField(HouseRule, blank=True, related_name="rooms")

    def __str__(self):
        return self.name

    # 어떤 상황이든(콘솔, 어드민, 뷰 등) 모델이 변경되면 저장하는 메서드
    def save(self, *args, **kwargs):
        # self.city = self.city[0].upper() + self.city[1:]
        # self.city = self.city.capitalize()
        self.city = self.city.title()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):

        all_reviews = self.reviews.all()
        all_ratings = 0
        for review in all_reviews:
            all_ratings += review.rating_average()
        try:
            return round(all_ratings / len(all_reviews), 2)

        except ZeroDivisionError:
            return 0

    def first_photo(self):
        try:
            photo, = self.photos.all()[:1]  # array의 원소를 변수에 할당하는 방법, unpacking values 라고 함
            return photo.file.url           # photo는 더이상 queryset이 아니고 인스턴스가 됨
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos =  self.photos.all()[1:5]
        return photos
    
    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        this_month = now.month
        next_month = this_month + 1
        next_year = this_year
        if this_month == 12:
            next_month = 1
            next_year = this_year + 1
        this_month_cal = Calendar(this_year, this_month)
        next_month_cal = Calendar(next_year, next_month)
        return [this_month_cal, next_month_cal]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from .models import Amenity, Facility, RoomType, Room, Photo


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere", required=False)
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(required=False, empty_label="Any kind", queryset=RoomType.objects.all())
    price = forms.IntegerField(required=False, min_value=1, max_value=300)
    guests = forms.IntegerField(required=False, min_value=1, max_value=10)
    bedrooms = forms.IntegerField(required=False, min_value=1, max_value=5)
    beds = forms.IntegerField(required=False, min_value=1, max_value=5)
    baths = forms.IntegerField(required=False, min_value=1, max_value=5)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(required=False, queryset=Amenity.objects.all(), widget=forms.CheckboxSelectMultiple)
    facilities = forms.ModelMultipleChoiceField(required=False, queryset=Facility.objects.all(), widget=forms.CheckboxSelectMultiple)


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ("file", "caption",)

    def save(self, room_pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = Room.objects.get(pk=room_pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = (
            "name",  
            "description",  
            "country",  
            "city", 
            "price", 
            "address", 
            "guests", 
            "beds", 
            "baths",
            "bedrooms", 
            "check_in",
            "check_out", 
            "instant_book", 
            "room_type", 
            "amenities",
            "facilities", 
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, UpdateView, View, FormView, CreateView
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import CreateView
from django_countries import countries
from users.mixins import LoggedInOnlyView
from .models import Room, RoomType, Amenity, Facility, HouseRule, Photo
from .forms import SearchForm, CreatePhotoForm, CreateRoomForm

class HomeView(ListView):

    """ HomeView Definition """

    model = Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"


class SearchView(View):

    """ SearchView Definition """

    def get(self, request):
        country = request.GET.get("country")
        city = request.GET.get("city")

        if city:

            form = SearchForm(request.GET)
            
            if form.is_valid():  # 유효성 검증을 통과한 폼 데이터는 cleaned_data에 담겨있음
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")
                
                filter_args = {}
                if city != "Anywhere":
                    filter_args["city__startswith"] = city
                
                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["guests__gte"] = bedrooms

                if beds is not None:
                    filter_args["guests__gte"] = beds

                if baths is not None:
                    filter_args["guests__gte"] = baths
                
                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["superhost"] = True

                rooms = Room.objects.filter(**filter_args)

                for amenity in amenities:
                    rooms = rooms.filter(amenities=amenity)

                for facility in facilities:
                    rooms = rooms.filter(facilities=facility)

                qs = rooms.order_by("created")

                paginator = Paginator(qs, 2)
                page = request.GET.get("page", 1)
                rooms = paginator.get_page(page)
                current_url = "".join(request.get_full_path().split("page")[0]) 
                if current_url[-1] != "&":
                    current_url = "".join(request.get_full_path().split("page")[0]) + "&"

                print("current_url: ", current_url)
                
                return render(request, "rooms/search.html", {"form": form, "page_obj": rooms, "current_url": current_url})

        else: 

            form = SearchForm()
        
        return render(request, "rooms/search.html", {"form": form})
   

class DetailRoomView(DetailView):

    """ RoomDetail Definition """

    model = Room


# Create form, Clean form, Validate form, 템플릿 렌더링, 리다이렉트(get_absolute_url) 다 해줌
class EditRoomView(LoggedInOnlyView, UpdateView):

    """ EditRoomView Definition """

    model = Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",  
        "description",  
        "country",  
        "city", 
        "price", 
        "address", 
        "guests", 
        "beds", 
        "baths",
        "bedrooms", 
        "check_in",
        "check_out", 
        "instant_book", 
        "room_type", 
        "amenities",
        "facilities", 
        "house_rules",
    )

    def get_object(self, queryset=None):   # return the object the view is displaying
        room = super().get_object(queryset=queryset)   
        if room.host.pk != self.request.user.pk:   # room의 host가 아닌 다른 유저가 수정하지 못하게끔 함
            raise Http404() 
        return room


class RoomPhotosView(LoggedInOnlyView, DetailView):

    model = Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):   # return the object the view is displaying
        room = super().get_object(queryset=queryset)   
        if room.host.pk != self.request.user.pk:   # room의 host가 아닌 다른 유저가 수정하지 못하게끔 함
            raise Http404()                        # DEBUG=False여야 내가 만든 404.html이 렌더링됨
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    print(f"Should delete {photo_pk} from {room_pk}")
    user = request.user
    try:
        # room 찾기
        room = Room.objects.get(pk=room_pk)
        # 1. user == room.host, delete photo
        if user == room.host:
            Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo deleted")
        # 2. user != room.host, error messages
        else:
            messages.error(request, "Photo can be deleted by host of this room.")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except Room.DoesNotExist:
        # room 없으면
        return redirect(reverse("core:home"))


class EditPhotoView(LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    """ EditPhotoView Definition """

    model = Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Caption of photo is updated"
    fields = ("caption",)

    def get_success_url(self):   
        """ if form_valid, save the form and return HttpResponseRedirect(self.get_success_url())"""
        room_pk = self.kwargs.get("room_pk")   # room_pk가 필요함
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class UploadPhotoView(LoggedInOnlyView, FormView):

    """ UploadPhotoView Definition """
    
    form_class = CreatePhotoForm
    template_name = "rooms/photo_create.html"

    def form_valid(self, form):
        room_pk = self.kwargs.get("pk")
        form.save(room_pk)
        messages.success(self.request, "Photo uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))


class CreateRoomView(LoggedInOnlyView, FormView):

    """ CreateRoomView Definition """

    form_class = CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()              # CreateRoomForm에서 만들어진 room을 리턴함
        room.host = self.request.user   # form 저장하기 전에 host에 인스턴스 넣어줌
        room.save()                     # 이제야 데이터베이스에 저장됨
        form.save_m2m()                 # save_m2m()은 데이터베이스에 인스턴스가 만들어져야 호출할 수 있음
        messages.success(self.request, "Room Created")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/detail.html
{% extends 'base.html' %}

{% block page_name %}
Home
{% endblock page_name %}

{% block content %}
<div>
    <h2>{{room.name}}</h2>
    <h3>{{room.description}}</h3>
</div>
<div>
    <h2>By: {{room.host.username}}
        {% if room.host.superhost %}
        (superhost)
        {% endif %}
    </h2>
    <h3>Amenities</h3>
    <ul>
        {% for a in room.amenities.all %}
        <li>{{a.name}}</li>
        {% endfor%}
    </ul>
    <h3>Facilities</h3>
    <ul>
        {% for f in room.facilities.all %}
        <li>{{f.name}}</li>
        {% endfor%}
    </ul>
    <h3>House Rules</h3>
    <ul>
        {% for r in room.house_rules.all %}
        <li>{{r.name}}</li>
        {% endfor%}
    </ul>

</div>

{% endblock content %}

templates/rooms/home.html
{% extends 'base.html' %}

{% block page_name %}
Home
{% endblock page_name %}

{% block content %}

{% for room in page_obj.object_list %}
<h3>{{room.name}} / ${{room.price}}</h3>
{% endfor %}

<h5>
    {% if page_obj.has_previous %}
        <a href="/?page={{page_obj.previous_page_number }}"><<</a>
    {% endif %}
        
    {{page_obj.number}} of {{page_obj.paginator.num_pages}}
    
    {% if page_obj.has_next %}
        <a href="/?page={{page_obj.next_page_number }}">>></a>
    {% endif %}
</h5>


{% endblock content %}

templates/rooms/photo_create.html
{% extends 'base.html' %}

{% block page_title %}
    Upload Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-24 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/room/room_form.html' with form=form cta="Upload Photo" %}
    </div>

{% endblock content %}

templates/rooms/photo_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Update Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-24 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/room/room_form.html' with form=form cta="Update Photo" %}
    </div>

{% endblock content %}

templates/rooms/room_create.html
{% extends 'base.html' %}

{% block page_title %}
    Create Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-24 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/room/room_form.html' with form=form cta="Create room" %}
    </div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends 'base.html' %}

{% load is_booked i18n on_favs %}

{% block page_title %}
    {{room.name}}
{% endblock page_title %}

{% block content %}

    <div class="container w-3/5 mx-auto h-50vh flex mb-10 pt-10">
        <div class="h-full w-1/2 bg-cover bg-center" style="background-image: url({{room.first_photo}});"></div>
        <div class="h-full w-1/2 px-2 flex flex-wrap">
            {% for photo in room.get_next_four_photos %}
                <div class="w-1/2 h-auto bg-cover bg-center" style="background-image: url({{photo.file.url}});"></div>
            {% endfor %}
        </div>
    </div>
    <div class="container w-3/5 mx-auto mb-56 flex justify-between">
        <div class="w-3/5">
            <div class="flex justify-between">
                <div class="mr-5 mb-5">
                    <h4 class="text-2xl font-medium mb-px">{{room.name}}</h4>
                    <span class="text-gray-700 font-light">{{room.city}}</span>
                </div>
                <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=room.host h_and_w='w-14 h-14' text='text-xl' %}
                    <span class="mt-2 text-gray-500">{{room.host.first_name}}</span>
                </a>
            </div>
            {% on_favs room as on_favs_bool %}
            
            {% if on_favs_bool %}
                <a href="{% url 'lists:toggle-room' room.pk %}?action=remove" class="mb-10 font-bold text-gray-300">
                    <i class="far fa-bookmark"></i>
                    {% trans 'Remove from Favourites' %}</a>
            {% else %}
                <a href="{% url 'lists:toggle-room' room.pk %}?action=add" class="mb-10 font-bold text-pink-500">
                    <i class="fas fa-bookmark"></i>
                    {% trans 'Save to Favourites' %}</a>
            {% endif %}
                
            <div class="flex border-section">
                <span class="mr-1 font-medium">{{room.guests}} guest{{room.guests|pluralize}} ·</span>
                <span class="mr-1 font-medium">{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}} ·</span>
                <span class="mr-1 font-medium">{{room.beds}} bed{{room.beds|pluralize}} ·</span>
                <span class="mr-1 font-medium">{{room.baths}} bath{{room.baths|pluralize}}</span>
            </div>
            <p class="border-section">
                {{room.description}}
            </p>
            <div class="border-section">
                <h4 class="font-medium text-xl mb-5">What this place offers</h4>
                {% for a in room.amenities.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-xl mb-5">Facilities</h4>
                {% for f in room.facilities.all %}
                    <li class="mb-2">{{f}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-2xl mb-4">
                    <i class="fas fa-star text-red-500"></i>
                    {{room.total_rating}} · {{room.reviews.count}} review{{room.reviews.count|pluralize}}
                </h4>
                <div class="mt-10">
                    {% for review in room.reviews.all  %}
                        <div class="my-3">
                            <div class="flex items-center mb-5">
                                <div>
                                    {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-14 h-14' text='text-xl' %}
                                </div>
                                <div class="flex flex-col ml-3">
                                    <span class="font-medium">{{review.user.first_name}}</span>
                                    <span class="text-sm text-gray-500">{{review.created | date:'F Y'}}</span>
                                </div>
                            </div>
                            <p class="pb-10">{{review.review}}</p>
                        </div>
                    {% endfor %}
                </div>
            </div> 
        </div>
        <div class="w-1/3">
            {% if request.user == room.host %}
            <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">Edit Room</a>
            {% else %}
                {% if not request.session.is_hosting %}
                    {% for calendar in room.get_calendars  %}
                    <div class="mb-20">
                        <span class="text-center font-medium text-lg block mb-8">
                            {{calendar.get_month}} / {{calendar.year}}
                        </span>
                        <div class="grid grid-cols-7 gap-2.5 justify-items-center mb-4 font-medium">
                            {% for day in calendar.day_names %}
                                <span>{{day}}</span>
                            {% endfor %}
                        </div>
                        <div class="grid grid-cols-7 gap-2.5 justify-items-center" >
                            {% for day in calendar.get_days  %}
                                {% is_booked room day as is_booked_bool %}
                                {% if day.number != 0 %}
                                    {% if is_booked_bool %}
                                        <span class="bg-gray-200 w-full text-center rounded-sm p-1 text-gray-300 line-through">{{day}}</span>
                                    {% elif day.past %}
                                        <span class="bg-gray-200 w-full text-center rounded-sm p-1 text-gray-300">{{day}}</span>
                                    {% else %}    
                                        <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}" class="bg-gray-200 w-full text-center rounded-sm p-1 hover:bg-pink-300 hover:text-white cursor-pointer">{{day}}</a>
                                    {% endif %}
                                {% else%}
                                    <span></span>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
            {% endif %}
        </div>
    </div>


{% endblock content %}

templates/rooms/room_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Update Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-24 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/room/room_form.html' with form=form cta="Update Room" %}
        <div class="mt-5">
            <a class="text-pink-500 font-medium" href="{% url 'rooms:photos' room.pk %}">Edit Photos</a>
        </div>
    </div>

{% endblock content %}

templates/rooms/room_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block page_title %}
    Home
{% endblock page_title %}

{% block content %}

    <div class="bg-gray-800 w-full h-58vh mb-5 bg-cover bg-center" style="background-image: url('/static/img/ocean.jpg')">

    </div>
    <div class="container mx-auto pb-10">
        <div class="flex flex-wrap -mx-10 mb-10">
            {% for room in rooms %}
                {% include 'mixins/room/room_card.html' with room=room %}
            {% endfor %}
        </div>
        
        <div class="flex items-center justify-center">
            {% if page_obj.has_previous %}
                <a href="/?page={{page_obj.previous_page_number }}" class="text-pink-400">
                    <i class="fas fa-chevron-left fa-lg"></i>
                </a>
            {% endif %}
            
            <span class="mx-10 font-medium text-lg">
                {% blocktrans with current_page=page_obj.number total_pages=page_obj.paginator.num_pages%}Page {{current_page}} of {{total_pages}}{% endblocktrans %}
            </span>
            
            {% if page_obj.has_next %}
                <a href="/?page={{page_obj.next_page_number }}" class="text-pink-400">
                    <i class="fas fa-chevron-right fa-lg"></i>
                </a>
            {% endif %}
        </div>
    </div>


{% endblock content %}

templates/rooms/room_photos.html
{% extends 'base.html' %}

{% block page_title %}
    {{room.name}}' Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container w-2/5 mx-auto my-24 flex flex-col">
        <div class="my-10 w-full ml-96 pl-52">
            <a href="{% url 'rooms:upload-photo' room.pk %}" class="text-center py-3 px-4 rounded-lg font-medium text-sm w-full text-white bg-red-500 ">Upload Photo</a>
        </div>
        
        {% for photo in room.photos.all %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32">
                    <span class="ml-5 text-base">{{photo.caption}}</span>
                </div>
                <div class="flex flex-col justify-around w-1/12">
                    <a class="text-center py-3 rounded-lg font-medium text-sm w-full text-white bg-blue-400" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Edit</a>
                    <a class="text-center py-3 rounded-lg font-medium text-sm w-full text-white bg-red-500" href="{% url 'rooms:delete-photo' room.pk photo.pk %}" onclick="return confirm('Do you want to delete this photo?')" >Delete</a>
                </div>
            </div>
        {% endfor %}
        <div class="flex justify-end mt-5">
            <a href="{% url 'rooms:edit' room.pk %}" class="text-red-500 font-medium text-lg">
                <i class="fas fa-arrow-circle-left"></i>
                <span>Back to Edit Room </span>
            </a>
        </div>
    </div>

{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <h2>Search!</h2>
    <form action="{% url 'rooms:search' %}" method="GET">
        {{form.as_p}}
        <button>Search</button>
    </form>
    <h3>Results</h3>
    <ul>
        {% for room in page_obj.object_list %}
        <li>
            {{room.name}}
        </li>
        {% endfor %}
    </ul>
    <div>
        {% if page_obj.has_previous %}
            <a href="{{current_url}}page={{page_obj.previous_page_number}}"><<</a>
        {% endif %}

        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

        {% if page_obj.has_next %}
            <a href="{{current_url}}page={{page_obj.next_page_number}}">>></a>
        {% endif %}
    </div>
{% endblock content %}