config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('sentry-debug/', trigger_error),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>/", views.go_conversations, name="go"),
    path("<int:pk>/", views.DetailConversationView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms.views import HomeView

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path("create/<int:room_pk>/<int:year>-<int:month>-<int:day>/", views.create_reservation, name="create"),
    path("<int:pk>/", views.DetailReservationView.as_view(), name="detail"),
    path("<int:pk>/<str:status>/", views.edit_reservation, name="edit"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

reservations/models.py
import datetime
from django.db import models
from django.utils import timezone
from core.models import AbstractTimeStamped


class BookedDay(models.Model):

    day = models.DateField()
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE, related_name="booked_day")

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Days"

    def __str__(self):
        return str(self.day)


class Reservation(AbstractTimeStamped):
    """Reservation Model Definition"""

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled"),
    )

    status = models.CharField(max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING)
    check_in = models.DateField()
    check_out = models.DateField()
    guest = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="reservations",
    )
    room = models.ForeignKey(
        "rooms.Room", on_delete=models.CASCADE, related_name="reservations",
    )

    def __str__(self):
        return f"{self.room} - {self.check_in}"

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now < self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        return now > self.check_out

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:           # 새로운 reservation 인스턴스 이면 BookedDay obj 만들어줌
            start = self.check_in
            end = self.check_out
            gap = end - start
            existing_booked_day = BookedDay.objects.filter(reservation__room=self.room, day=start).exists()
            if not existing_booked_day:
                super().save(*args, **kwargs)    # create reservation instance first
                for i in range(gap.days):
                    day = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)
                return
        return super().save(*args, **kwargs)

reservations/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.views.generic import View
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from rooms.models import Room
from reviews.forms import CreateReviewForm
from .models import BookedDay, Reservation


class CreateError(Exception):
    pass


@login_required
def create_reservation(request, room_pk, year, month, day):
    try:
        day = datetime.datetime(year, month, day)
        room = Room.objects.get(pk=room_pk)
        BookedDay.objects.get(day=day, reservation__room=room)
        raise CreateError()    # BookedDay가 있다면 예약할 수 없으니까 error
    except (Room.DoesNotExist, CreateError):
        messages.error(request, "Can't Reserve this room") 
        return redirect(reverse("core:home"))
    except BookedDay.DoesNotExist:
        reservation = Reservation.objects.create(
            guest=request.user,
            room=room,
            check_in=day,
            check_out=day + datetime.timedelta(days=1),
        )
        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))

    
class DetailReservationView(View):
    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        reservation = Reservation.objects.get_or_none(pk=pk)  # create get_or_none model manager
        if not reservation or (
            reservation.guest != self.request.user 
            and reservation.room.host != self.request.user
        ):
            raise Http404()
        form = CreateReviewForm()
        return render(self.request, "reservations/detail.html", {"reservation": reservation, "form": form})


def edit_reservation(request, pk, status):
    reservation = Reservation.objects.get_or_none(pk=pk)
    print(reservation) 
    if not reservation or (
        reservation.guest != request.user 
        and reservation.room.host != request.user
    ):
        raise Http404()
    if status == "confirm":
        reservation.status = Reservation.STATUS_CONFIRMED
    elif status == "cancel":
        reservation.status = Reservation.STATUS_CANCELED
        BookedDay.objects.filter(reservation=reservation).delete()
    reservation.save()
    messages.success(request, "Reservation Updated")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))

templates/reservations/detail.html
{% extends 'base.html' %}

{% block page_title %}
    reservation {{reservation.check_in}}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container w-2/5 mx-auto my-24 flex flex-col">
        {% if reservation.check_in.month == reservation.check_out.month and reservation.check_in.year == reservation.check_out.year %}
            <span class="text-gray-400 font-normal mt-3 -mb-8">{{reservation.room.address}} · {{reservation.check_in|date:'M d'}} - {{reservation.check_out|date:'d, Y' }}</span>
        {% elif reservation.check_in.year == reservation.check_out.year %}
            <span class="text-gray-400 font-normal -mb-8">{{reservation.room.address}} · {{reservation.check_in|date:'M d'}} - {{reservation.check_out|date:'M d, Y' }}</span>
        {% else %}
            <span class="text-gray-400 font-normal -mb-8">{{reservation.room.address}} · {{reservation.check_in}} - {{reservation.check_out}}</span>
        {% endif %}
            
        <span class="text-3xl font-bold border-section mb-8">Your stay at {{reservation.room.host}}'s place</span>
        <div class="bg-cover bg-center h-64 rounded-lg" style="background-image: url({{reservation.room.first_photo}});"></div>
        <a href="{% url 'rooms:detail' reservation.room.pk %}" class="border-section text-lg font-bold">{{reservation.room.name}}</a>
        <div class="border-section flex justify-between">
            <p class="text-lg font-bold">Reservation Status</p>
            <span class="text-base font-normal pr-10 {% if reservation.status == 'pending' %} text-yellow-500 {% elif reservation.status == 'canceled' %} text-red-600 {% else %} text-green-600 {% endif %}">{{reservation.get_status_display}}</span>
        </div>
        
        <div class="border-section flex justify-between">
            <div class="flex flex-col">
                <span class="font-bold text-lg">Check-in</span>
                <span>{{reservation.check_in}}</span>
            </div>
            <div class="border-r"></div>
            <div class="flex flex-col relative right-40">
                <span class="font-bold text-lg">Check-out</span>
                <span>{{reservation.check_out}}</span>
            </div>
        </div>
        <div class="flex justify-between py-5 border-b hover:bg-gray-50">
            <a class="text-lg font-medium w-full" href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk %}"><i class="fas fa-comment-alt pr-3"></i>Message Host</a>
            <i class="fas fa-chevron-right cursor-pointer"></i>
        </div>
        <div class="flex justify-between border-section">
            <div class="flex flex-col">
                <span class="text-xl font-bold">Your Host, {{reservation.room.host.first_name}}</span>
                <a href="{% url 'users:profile' reservation.room.host.pk %}"><span class="font-medium underline">Show profile</span></a>
            </div>
            <div class="flex flex-col items-center">
                {% include "mixins/user_avatar.html" with user=reservation.room.host h_and_w='w-14 h-14' text='text-xl' %}
            </div>
        </div>
        {% if reservation.status != 'canceled' %}
            {% if reservation.status == 'confirmed' and reservation.is_finished %}
                <div class="border-section">
                    <span class="text-xl font-bold">Write your review</span>
                    <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-3/4 mt-2">
                        {% csrf_token %}
                        {{form}}
                        <button class="btn-link mt-5">Submit Review</button>
                    </form>
                </div>
            {% else %}
                <div class="py-20 text-center">
                    {% if reservation.status == 'pending' %}
                        <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}" class="btn-link px-10 mr-8">Cancel Reservation</a>
                        {% if reservation.room.host == user %}
                            <a href="{% url 'reservations:edit' reservation.pk 'confirm' %}" class="btn-link px-10">Confirm Reservation</a>
                        {% endif %}
                    {% endif %}
                </div>
            {% endif %}
        {% endif %}
    </div>

{% endblock content %}