config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('sentry-debug/', trigger_error),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms.views import HomeView

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views


app_name = "rooms"

urlpatterns = [
    path("search/", views.SearchView.as_view(), name="search"),
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.DetailRoomView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.UploadPhotoView.as_view(), name="upload-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

users/forms.py
from django import forms
from django.core import exceptions
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.password_validation import validate_password
from django.core import validators
from django.forms import widgets
from .models import User

class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password"}))

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


# form.Form을 상속받는 경우
# class SignupForm(forms.Form):

#     first_name = forms.CharField(max_length=80)
#     last_name = forms.CharField(max_length=80)
#     email = forms.EmailField()
#     password = forms.CharField(widget=forms.PasswordInput)
#     password1 = forms.CharField(widget=forms.PasswordInput, label="Comfirm Password")

#     def clean_email(self):
#         email = self.cleaned_data.get("email")
#         try:
#             User.objects.get(email=email)
#             raise forms.ValidationError("User already exist with this email")
#         except User.DoesNotExist:
#             return email

#     def clean_password1(self):
#         password = self.cleaned_data.get("password")
#         password1 = self.cleaned_data.get("password1")

#         if password != password1:
#             raise forms.ValidationError("Password confirmation does not match")
#         else:
#             return password

#     def save(self):
#         first_name = self.cleaned_data.get("first_name")
#         last_name = self.cleaned_data.get("last_name")
#         email = self.cleaned_data.get("email")
#         password = self.cleaned_data.get("password")

#         user = User.objects.create_user(email, email, password)
#         user.first_name = first_name
#         user.last_name = last_name
#         user.save()


# forms.ModelForm을 상속받는 경우
class SignupForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email"}),
        }

    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}), validators=[validate_password])
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}), label="Comfirm Password")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            User.objects.get(email=email)
            raise forms.ValidationError("User already exist with this email")
        except User.DoesNotExist:
            return email
            
    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)  # create object, but object hasn't yet been saved to the database 
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

    
class ProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "gender",
            "bio",
            "birthdate",
            "language",
            "currency",)
        
        widgets = {
            "first_name" : forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name" : forms.TextInput(attrs={"placeholder": "Last Name"}),
            "bio" : forms.Textarea(attrs={"placeholder": "Bio"}),
            "birthdate" : forms.DateInput(attrs={"placeholder": "Birthdate"}),
            "language" : forms.Select(attrs={"value": "aa"}),
        }

users/views.py
import os
import requests
from django.conf import settings
from django.utils import translation
from django.http import HttpResponse
from django.views.generic.base import RedirectView
from django.views import View
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.files.base import ContentFile
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect
from .forms import LoginForm, SignupForm, ProfileForm
from .models import User
from .mixins import LoggedOutOnlyView, LoggedInOnlyView, EmailLoginOnlyView

# View 상속하는 경우
# class LoginView(View):

#     def get(self, request):
#         form = LoginForm(initial={"email": "ojo1001@naver.com"})
#         return render(request, "users/login.html", {"form": form})

#     def post(self, request):
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             email = form.cleaned_data.get("email")
#             password = form.cleaned_data.get("password")
#             user = authenticate(request, username=email, password=password)
#             if user is not None:
#                 login(request, user)
#                 return redirect(reverse("core:home"))

#         return render(request, "users/login.html", {"form": form})

# FormView 상속하는 경우
class LoginView(LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = LoginForm
    # success_url = reverse_lazy("core:home")  # 클래스안에서는 reverse_lazy 씀
    initial = {"email": "admin@admin.com"}

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.

        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)  # get_success_url 호출함
    
    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    logout(request)
    messages.info(request, "See you later")
    return redirect(reverse("core:home"))


class SignupView(FormView):
    template_name = "users/signup.html"
    form_class = SignupForm
    success_url = reverse_lazy("core:home")  

    def form_valid(self, form):
        form.save()         # form.is_valid() 가 True라면 save
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # To do: add sucess message
    except User.DoesNotExist:
        # To do: add error message 
        pass
    return redirect(reverse("core:home"))


class GithubException(Exception):
    pass


# pinkbnb -> github
def github_login(request):
    client_id = os.environ.get("GITHUB_CLIENT_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/github/callback/"
    return redirect(f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}")


# when user clicked accept, github -> pinkbnb
def github_callback(request):
    try: 
        code = request.GET.get("code", None)
        client_id = os.environ.get("GITHUB_CLIENT_ID")
        client_secret = os.environ.get("GITHUB_CLIENT_SECRET")
        if code is not None:                         # 1. callback으로 code 받았는지 확인
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"}
                )
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:                    # 2. 시간 초과, code 두번 이상 사용 등으로 error가 있다면 redirect / json에 에러가 있는지 체크
                raise GithubException("Can't get access token")
            else:                                    # 3. 에러가 없으면, callback로 받은 code로 access_token 발급 받아서  
                access_token = token_json.get("access_token")
                profile_request = requests.get(      # 3. github api에 requests 보내기
                    "https://api.github.com/user", 
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json"
                    },
                )
                profile_json = profile_request.json() # 4. response로 user 정보 받음
                username = profile_json.get("login", None)
                if username is not None:              # 5. github에 user 정보가 있다면, name, email, bio 가져오기
                    name = profile_json.get("name")
                    email = profile_json.get("email")
                    bio = profile_json.get("bio")
                    try:                                     # 6. pinkbnb에 해당 이메일로 이미 유저가 존재하는데, 그 유저가 이미 github의 로그인 인증을 거쳤다면 로그인 시켜주기
                        user = User.objects.get(email=email) 
                        if user.login_method != User.LOGIN_GITHUB: 
                            raise GithubException(f"Please log in with: {user.login_method}") # 6-1. 다른 login_method로 만들어진 유저라면 에러 발생
                                
                    except User.DoesNotExist:                # 7. pinkbnb에 해당 이메일의 유저가 없다면 만들어주기
                        user = User.objects.create(
                            username=email, 
                            first_name=name, 
                            email=email,
                            bio=bio,
                            login_method=User.LOGIN_GITHUB,
                            email_verified=True,
                        )
                        user.set_unusable_password()
                        user.save()

                    login(request, user)
                    messages.success(request, f"Welcome back {user.first_name}")
                    
                    return redirect(reverse("core:home"))
                else:                                        # 8. user 정보가 없다면 에러 발생
                    raise GithubException("Can't get your profile")
        else:
            raise GithubException("Can't get code")
    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))     


class KakaoException(Exception):
    pass


def kakao_login(request):
    client_id = os.environ.get("KAKAO_CLIENT_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback/"

    return redirect(f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code")
    

def kakao_callback(request):
    try:
        # access_token 받기
        code = request.GET.get("code")
        client_id = os.environ.get("KAKAO_CLIENT_ID")
        redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback/"
        token_request = requests.post(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&code={code}&redirect_uri={redirect_uri}",
           )
        token_json = token_request.json()
        # print(token_json)
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("Can't get authorization code.")
        access_token = token_json.get("access_token")
        
        # 카카오 API 호출하기
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"}
            )
        profile_json = profile_request.json()
        # print(profile_json)
        email = profile_json.get("kakao_account").get("email", None)
        if email is None:
            raise KakaoException("Plase also give me your email")
        nickname = profile_json.get("properties").get("nickname")
        profile_img = profile_json.get("properties").get("profile_image")
        # print(profile_img)
        try:
            user = User.objects.get(email=email)
            if user.login_method != User.LOGIN_KAKAO:
                raise KakaoException(f"Please log in with: {user.login_method}")
                
        # API로 가져온 사용자 정보로 유저 생성하기
        except User.DoesNotExist:
            user = User.objects.create(
                username=email,
                first_name=nickname,
                email=email,
                login_method=User.LOGIN_KAKAO,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()
            if profile_img is not None:
                photo_request = requests.get(profile_img)
                user.avatar.save(f"{nickname}-avatar", ContentFile(photo_request.content))
        
        login(request, user)
        messages.success(request, f"Welcome back {user.first_name}")
        return redirect(reverse("core:home"))

    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):

    model = User
    context_object_name = "user_obj"


# UpdateView를 사용하면 form을 따로 정의하지 않아도 됨
# form에 많은 컨트롤이 필요하다면 따로 사용하는게 좋음
class UpdateProfileView(LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    

templates/users/login.html
{% extends "base.html" %}

{% block page_title %}
    Log In
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-1/2 md:w-1/2 xl:w-1/4 mx-auto my-24 flex flex-col items-center border p-6 border-gray-400">
        
        {% include 'mixins/auth/auth_form.html' with form=form cta="Log in" %}
        
        <div class="mt-5">
            <span class="mr-2">Don't have an account?</span>
            <a class="text-pink-500 font-medium" href="{% url 'users:signup' %}">Sign up</a>
        </div>
        {% include 'partials/social_login.html' %}
    </div>
        
    
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_title %}
    Sign Up
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class="container lg:w-1/2 md:w-1/2 xl:w-1/4 mx-auto my-24 flex flex-col items-center border p-6 border-gray-400">
    
    {% include 'mixins/auth/auth_form.html' with form=form cta="Sign up" %}

    <div class="mt-5">
        <span class="mr-2">Have an account?</span>
        <a class="text-pink-500 font-medium" href="{% url 'users:login' %}">Log in</a>
    </div>
    {% include 'partials/social_login.html' %}
</div>
    
    
{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}

{% block page_title %}
    Update Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-1/2 md:w-1/2 xl:w-1/4 mx-auto my-24 flex flex-col items-center border p-6 border-gray-400">
        
            {% include 'mixins/auth/auth_form.html' with form=form cta="Update Profile" %}
            {% if object.login_method == "email" %}
                <div class="mt-5">
                    <a class="text-pink-500 font-medium" href="{% url 'users:password' %}">Change Password</a>
                </div>
            {% endif %}
        </div>
        
{% endblock content %}

templates/users/update_password.html
{% extends "base.html" %}

{% block page_title %}
    Update Password
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="min-h-75vh">
        <div class="container lg:w-1/2 md:w-1/2 xl:w-1/4 mx-auto my-24 flex flex-col items-center border p-6 border-gray-400">
            
            {% include 'mixins/auth/auth_form.html' with form=form cta="Update Password" %}
            
        </div>
    </div>
    
{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{user_obj.first_name}}'s Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="min-h-75vh">
        <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-24 flex flex-col items-center border p-6 border-gray-400">
            
            {% include 'mixins/user_avatar.html' with user=user_obj %}
            
            <div class="flex items-center">
                <span class="text-2xl mt-2">{{user_obj.first_name}}</span>
                {% if user_obj.superhost %}
                    <i class="fas fa-check-circle text-red-500 ml-1"></i>
                {% endif %}
            </div>
            
            <span class="text-lg mb-5">{{user_obj.bio}}</span>
            
            {% if user == user_obj %}
                <a href="{% url 'users:update' %}" class="btn-link mb-3">Edit Profile</a>
            {% endif %}
        </div>

        {% if user_obj.rooms.count > 0 %}
            <h3 class="mb-12 text-2xl text-center font-medium">{{user_obj.first_name}}'s Room </h3>
            <div class="container mx-auto pb-10">
                <div class="flex flex-wrap mx-20 mb-10">
                    {% for room in user_obj.rooms.all %}
                        {% include 'mixins/room/room_card.html' with room=room %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {% if user_obj.reservations.count > 0 %}
        <h3 class="my-12 text-2xl text-center font-medium">{{user_obj.first_name}}'s Reservations</h3>
        <div class="container mx-auto py-10">
            <ul class="flex flex-wrap mx-20 mb-10">
                <li class="flex justify-around p-2 mb-2 w-full text-xl font-bold">
                    <span class="mx-40">Room Name</span>
                    <span>Check-In</span>
                    <span>Check-Out</span>
                    <span>Status</span>
                </li>
                {% for reservation in user_obj.reservations.all|dictsortreversed:"created" %}
                <a href="{% url 'reservations:detail' reservation.pk %}" class="w-full m-1"><li class="flex justify-around bg-gray-200 p-2 rounded-md">
                    <span class="font-medium w-2/6">{{reservation.room}}</span>
                    <span class="font-medium">{{reservation.check_in}}</span>
                    <span class="font-medium">{{reservation.check_out}}</span>
                    <span class="font-medium">{{reservation.status}}</span>
                </li></a>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>
    
    {% endblock content %}